export const langs = {
  'Control character': '控制字符',
  'Selection deleted': '已删除所选内容',
  'Folded lines': '折叠所有行',
  'Unfolded lines': '展开所有行',
  to: '去',
  'folded code': '折叠代码',
  unfold: '展开',
  'Fold line': 'Fold',
  'Unfold line': 'Unfold',
  'Go to line': '去往指定行',
  go: '确定',
  Find: '查找',
  Replace: '替换',
  next: '下一个',
  previous: '上一个',
  all: '全部',
  'match case': '区分大小写',
  'by word': '单词匹配',
  replace: '替换',
  'replace all': '替换全部',
  close: '关闭',
  'current match': '当前匹配',
  'replaced $ matches': '已替换 $ 匹配项',
  'replaced match on line $': '已替换  $ 行中的匹配项',
  'on line': '一行',
  Completions: '补全',
  Diagnostics: '诊断',
  'No diagnostics': '无诊断信息',
}
