export const english = {
  "Control character": "Control character",
  "Selection deleted": "Selection deleted",
  "Folded lines": "Folded lines",
  "Unfolded lines": "Unfolded lines",
  to: "to",
  "folded code": "folded code",
  unfold: "unfold",
  "Fold line": "Fold line",
  "Unfold line": "Unfold line",
  "Go to line": "Go to line",
  go: "go",
  Find: "Find",
  Replace: "Replace",
  next: "next",
  previous: "previous",
  all: "all",
  "match case": "match case",
  "by word": "by word",
  replace: "replace",
  "replace all": "replace all",
  regexp: "regexp",
  close: "close",
  "current match": "current match",
  "replaced $ matches": "replaced $ matches",
  "replaced match on line $": "replaced match on line $",
  "on line": "on line",
  Completions: "Completions",
  Diagnostics: "Diagnostics",
  "No diagnostics": "No diagnostics",
};
